### ISSUE TITLE
Block Explorer design

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/HS-Design#1]
- Search bar
- Latest blocks
   Height
   Age (Time)
   Transactions
   Total Sent
   Total Fees
   Block Size
   Relayed by
   Reward
   Hash
- Latest transactions
  Hash
  Value
- Block info
- Transaction Info

**Comment by esengulov** [comment]
looks good, https://btc.horizontalsystems.xyz
let's keep it this way for the time being
