### ISSUE TITLE
Redesign Look for https://horizontalsystems.io

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#10]
Text:

We believe in Unconditional Right to freedom. People are born free. Everything we do is aimed at enforcing this personal freedom on a global scale.

We build **Unstoppable Code**: engineered to resist censorship and remain online indefinitely. Your freedom can't be shut down. Can't be censored. Can't be cheated.

We happen to make great applications. Applications that enforce and guarantee your freedom.

**Comment by TalgatNurdinov** [comment]
<img width="619" alt="Screen Shot 2019-05-03 at 11 12 31 AM" src="https://user-images.githubusercontent.com/42367908/57120784-701cc880-6d95-11e9-914a-134654ff3379.png">
https://zpl.io/b647DYm
