### ISSUE TITLE
Icons for new BEP2 tokens

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/HS-Design#103]
1) THKDB (TrueHKD)
2) TUSDB (TrueUSD)
3) TAUDB (TrueAUD)
4) USDSB (USDS)
5) HYN (Hyperion Token)
6) DEFIDeFi Token
7) Rune (Rune)
8) MATICMatic Token
9) ONEHarmony.One
10) IRISIRIS Network
11) ETH (ETHBEP2)
12) SWINGBY (Swingby Token)
13) CHZ (Chiliz)
14) Share token (SHR)
15) USDT (USDTBEP2)
16) WICCWaykiChain Coin
17) WRX (WazirX Token)
18) COS (Contentos)
19) LTO-BDF (LTO Network)
20) MTXLT (Tixl)

**Comment by kansalt** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=9433%3A2907
