### ISSUE TITLE
icons for new erc20 tokens

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/HS-Design#109]
- [x] The Graph (GRT)
- [x] Wrapped Zcash
- [x] CryptoFranc (XCHF)
- [x] Wrapped CryptoKitties
- [x] Panvala pan (PAN)
- [x] Magnolia Token
- [x] Gnosis Token (GNO)
- [x] DHEGD
- [x] SUSD

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=25356%3A447
