### ISSUE TITLE
new erc20 icons

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/HS-Design#110]
- [x] reflect.finance (RFI)
- [x] Orion Protocol (ORN)
- [x] Base Protocol (BASE)
- [x] Fyooz (FYZ)
- [x] Linear (LINA)

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=25453%3A3219
