### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/HS-Design#118]
- [x] Shabu Shabu (KOBE)
- [x] Axie Infinity (AXS)
- [x] VeThor Token (VTHO)
- [x] Mask Network (MASK)
- [x] Reef Finance (REEF)
- [x] Zilliqa (ZIL)
- [x] LUKSO Token (LYXE)
- [x] Sora Validator Token (VAL)
- [x] Uquid Coin (UQC)
- [x] JulSwap (JULD)
- [x] Raydium (RAY)
- [x] NFTX (NFTX)
- [x] Power Ledger (POWR)

**Comment by kansalt** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=30084%3A189713
