### ISSUE TITLE
Team avatars on Github.com/horisontalsystems

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#12]
provide team members with avatars so that the page looks better overall. Maybe add some branding there

**Comment by TalgatNurdinov** [comment]
![Esen@3x](https://user-images.githubusercontent.com/42367908/57764517-701db080-7725-11e9-9ff4-f6416045c009.png)
![Raf@3x](https://user-images.githubusercontent.com/42367908/57764518-70b64700-7725-11e9-8c42-95ed2d11bb9f.png)
![Chyngyz](https://user-images.githubusercontent.com/42367908/57764520-70b64700-7725-11e9-9896-a4e733777e2e.png)
![ermat](https://user-images.githubusercontent.com/42367908/57764521-70b64700-7725-11e9-9563-4931490b6d02.png)
![Nurkaly](https://user-images.githubusercontent.com/42367908/57764522-70b64700-7725-11e9-86e0-72f81130fb55.png)
![Diana@3x](https://user-images.githubusercontent.com/42367908/57764523-714edd80-7725-11e9-92c8-e9fb876164dd.png)
![Talgat](https://user-images.githubusercontent.com/42367908/57764524-714edd80-7725-11e9-804c-f81feeaac6b6.png)
![moi](https://user-images.githubusercontent.com/42367908/57764525-714edd80-7725-11e9-90fe-73b8c5830328.png)
![Aibek@3x](https://user-images.githubusercontent.com/42367908/57764526-71e77400-7725-11e9-966a-f0788501bce9.png)
![Maxim@3x](https://user-images.githubusercontent.com/42367908/57764527-71e77400-7725-11e9-8389-1b6de2104f0b.png)
![Arslan](https://user-images.githubusercontent.com/42367908/57764528-71e77400-7725-11e9-8146-85bd91f7fb51.png)
![Anton@3x](https://user-images.githubusercontent.com/42367908/57764529-71e77400-7725-11e9-9cbb-57ddc3c09a69.png)
![kerim](https://user-images.githubusercontent.com/42367908/57764530-72800a80-7725-11e9-843e-d0697f98d1fe.png)
![Bakyt@3x](https://user-images.githubusercontent.com/42367908/57764531-72800a80-7725-11e9-85f1-852c0b9975c8.png)
