### ISSUE TITLE
Make logos for "Treasuries" companies (new)

### ISSUE THREAD

**Issue by Dadybayo** [horizontalsystems/HS-Design#129]
- Core Scientific (NADQ:CORZ) 
- Fidelity Advantage Bitcoin (CSE:FBTC)
- Cathedra Bitcoin Inc. (TSXV:CBIT)

**Comment by TalgatNurdinov** [comment]
@Dadybayo https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=9433%3A2907
