### ISSUE TITLE
lock screen: maybe we should use lock icon instead of "passcode" text

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#15]
I think it will look better.

what you do think?

**Comment by TalgatNurdinov** [comment]
We set this icon to block for incorrect passcode
![IMG_B602A2A821B6-1](https://user-images.githubusercontent.com/42367908/58315434-60901d00-7e33-11e9-8a57-e9ab8a4cb9ca.jpeg)
