### ISSUE TITLE
wallet site need to list wallet features

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#16]
I see it as a list of features, maybe somewhere between 5-10 items, below the download buttons

**Comment by TalgatNurdinov** [comment]
- Multi language
- Smart Fee
- Easy Backup and Restore
- Real time exchange rate
- Dark and Light native interface 
- Bitcoin / Bitcoin Cash / Dash / Ethereum / ERC-20 Coins
- No data collection
- Non custodial
- Cannot fail

**Comment by TalgatNurdinov** [comment]
list of features reduced to 6
https://zpl.io/aRx8ZPz

**Comment by TalgatNurdinov** [comment]
https://zpl.io/awJd0md
<img width="1021" alt="Screen Shot 2019-05-17 at 3 08 58 PM" src="https://user-images.githubusercontent.com/42367908/57916965-b73aab80-78b5-11e9-8cba-276135332f17.png">

**Comment by esengulov** [comment]
@TalgatNurdinov 

we need to add somewhere that wallet supports Bitcoin, Bitcoin Cash, Ethereum, Dash, ERC20 tokens

**Comment by TalgatNurdinov** [comment]
https://zpl.io/awJd0md
<img width="842" alt="Screen Shot 2019-05-23 at 4 23 42 PM" src="https://user-images.githubusercontent.com/42367908/58245683-26614580-7d77-11e9-9169-c85f1c6af390.png">
