### ISSUE TITLE
Think through "Restore" Wallet screens

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#17]
At the moment the restore is process is not entirely decentralized. The wallet restores through a specific API to ensure faster restore progress. 

This is being changed this very moment because the faster restore comes with a privacy leak risk. We need to provide user with an option to choose what kind of restore options to proceed with. 

Basically, for each blockchain the user will get two options(below) and a description highlighting differences between the restore type for the given blockchain:

1 - Fast Restore
Fast but not private

2- Slow (Very slow)
Slow but private

**Comment by TalgatNurdinov** [comment]
<img width="733" alt="Screen Shot 2019-05-28 at 2 45 18 PM" src="https://user-images.githubusercontent.com/42367908/58464372-62b9ea80-8157-11e9-81e1-fc338f9bedf3.png">

https://zpl.io/2j5oReA
https://zpl.io/amdEwr9

**Comment by TalgatNurdinov** [comment]
Last update (iOS)
<img width="1144" alt="Screen Shot 2019-05-30 at 2 35 02 PM" src="https://user-images.githubusercontent.com/42367908/58620132-2669c400-82e8-11e9-861d-ee2cc029a7d7.png">

https://zpl.io/25JKmM0
https://zpl.io/aNmAvA4
zpl.io/aBRlAlp

**Comment by TalgatNurdinov** [comment]
Instead settings icon should be "more" icon. because erc-20 coins can't disabled after adding
<img width="381" alt="Screen Shot 2019-05-30 at 2 44 54 PM" src="https://user-images.githubusercontent.com/42367908/58620690-8a40bc80-82e9-11e9-88b6-d09745b78888.png">

**Comment by esengulov** [comment]
designs here are outdated, the actual implementation has different mockups

- https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/634
- https://github.com/horizontalsystems/unstoppable-wallet-android/issues/918

already implemented. closing the issue
