### ISSUE TITLE
"active" indicator pending transactions 

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#18]
Pending transactions on Transactions Tab may be perceived as though they’ve failed/stuck because in some case the transaction may remain in pending for hours, especially ones that weren't sent with the low fee. 

The pending (in progress) activity should be show animated to give user an impression that something is happening. Maybe something similar to Telegram's typing indicator dots "..."?

i0S issue: https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/1119
Android issue: https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1378

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=46%3A4
