### ISSUE TITLE
Test the wallet layout with the native font settings increased/decreased

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#19]
here is the recent layout bug we encountered, https://github.com/horizontalsystems/unstoppable-wallet-android/issues/920

To make sure that all other elements are playing nicely test the entire app GUI on following settings.

- [x] iOS, with font settings below OS default value
- [x] iOS, with font settings above OS default value
- [x] Android, with font settings below OS default value
- [x] Android, with font settings above OS default value

**Comment by TalgatNurdinov** [comment]
i think we will ignore the customization font size and style in our app because big sizes may doesnt fit in some places of our controllers. 
On iOS already ignored.
