### ISSUE TITLE
View Options on Balance Tab

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#20]
Let's experiment with an idea.

As a wallet user with a balance on a number on a number of coins I am missing some view features that would make the usage experience better.

These are:

- ability to blur large amount on the balance tab itself as well as individual coins.
- ability to hide (from view) coins with low balance (ex: below 1$)
- ability to sort coins by total value 

Let's try adding an icon (may an EYE icon or something) that would appear on top right corner. Clicking on it  would drop down menu with three options

- Blur Large Amounts
- Hide Low Amounts
- Sort By Amount

On item click it will get the checkmark and apply the setting. Clicking elsewhere on the screen would dismiss the icons.

The icon will become visible and active only when:

- the wallet is in synced state
- when there are at least X coins with balance.

**Comment by TalgatNurdinov** [comment]
![Balance  Copy 11@2x](https://user-images.githubusercontent.com/42367908/59423746-9140f200-8df4-11e9-9ae3-ccb6b9f845ff.png)
![Balance  Copy 12@2x](https://user-images.githubusercontent.com/42367908/59423747-9140f200-8df4-11e9-803f-ef8ef7aea251.png)

last version

**Comment by esengulov** [comment]
@TalgatNurdinov  please also show how the sorting menu will look like for both views

**Comment by TalgatNurdinov** [comment]
<img width="798" alt="Screen Shot 2019-06-18 at 8 49 19 PM" src="https://user-images.githubusercontent.com/42367908/59694520-96de7380-920a-11e9-9e82-cb58b5238a82.png">
