### ISSUE TITLE
New Wallet : Default State 

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#24]
- [ ] Based on the feedback we decided to keep initial state to two coins: Bitcoin and Ethereum
- [ ] it was also reported that "+" add button is not self evident, therefore let's try "Add" or "Add Coins" text instead

**Comment by TalgatNurdinov** [comment]
<img width="513" alt="Screen Shot 2019-06-11 at 6 29 41 PM" src="https://user-images.githubusercontent.com/42367908/59272037-e6ef9000-8c76-11e9-8f6a-e07d9c2c5e10.png">
https://zpl.io/25OoL5o

**Comment by TalgatNurdinov** [comment]
Android 

<img width="512" alt="Screen Shot 2019-06-11 at 6 35 21 PM" src="https://user-images.githubusercontent.com/42367908/59272379-bcea9d80-8c77-11e9-95cf-7d74c7a06ad7.png">

https://zpl.io/Vkwl7NG

**Comment by esengulov** [comment]
The issue is already implemented and no longer relevant
