### ISSUE TITLE
New Description for App Store / Play Market

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#25]
Investing in Bitcoin and other cryptocurrencies should be easy and available to everyone.

Our UNSTOPPABLE wallet was built to enable any freedom-loving individual to safely store, monitor, and exercise full control over their Bitcoins and other crypto assets like never before.

1) OWN YOUR CRYPTO

If you don’t own private keys (which give you ownership over crypto assets), you don’t own Bitcoin. 

Most crypto wallets are custodials where the wallet provider controls your private keys. UNSTOPPABLE wallet is a non-custodial wallet. The private keys never leave your phone. Only you are in control.

2) KEEP YOUR CRYPTO SAFE 

When you enable the lock code on your phone’s operating system, no one will be able to access your wallet funds even if your phone is stolen or lost.

In case of a device loss, UNSTOPPABLE makes it easy to restore your wallet on another device.

3) BE INDEPENDENT 

UNSTOPPABLE wallet was engineered to remain online and fully-functional indefinitely.

Transfer Bitcoins and other crypto regardless of local government regulations. No entity can stop you from sending or receiving crypto or force UNSTOPPABLE to stop working. Your wallet will always be online.

4) STAY PRIVATE

When using UNSTOPPABLE, you are connecting directly to decentralized blockchains without any restrictions or intermediaries. Only you can see your Bitcoins and other crypto balances as well as transactions.

There are no accounts, emails, phone numbers, identity checks, or third-party servers storing any private data.

5) UNIVERSAL WALLET

Transfer, store, and monitor prices for 60 decentralized currencies such as Bitcoin and Ethereum as well as blockchain-based tokens.

Supported Cryptocurrencies:

- Bitcoin (BTC)
- Ethereum (ETH)
- EOS (EOS)
- Binance DEX Chain (BNB)
- Dash (DASH)
- Bitcoin Cash (BCH)

EOS-based Projects:

- EOSDT https://eosdt.com/eosdt
- Everipedia https://everipedia.org/about
- MEET.ONE https://meet.one
- Native Utility Token https://eosdt.com/governance
- Newdex https://newdex.io
- Paytomat https://paytomat.com
- Prospectors Gold https://prospectors.io

Ethereum-based Projects:

0x https://0x.org
Aelf https://aelf.io
Bancor https://www.bancor.network
Basic Attention Token https://basicattentiontoken.org
Binance Coin https://www.binance.com/en/bnb
ChainLink https://chain.link
Crypto.com https://crypto.com/en/token.html
Dai https://makerdao.com/en/dai
Decentraland https://decentraland.org
Digix DAO / Gold https://digix.global/dgx
Enjin https://enjincoin.io
Gemini Dollar https://gemini.com/dollar
Golem https://golem.network
Holo https://holochain.org
Huobi Token https://www.hbg.com/en-us/ht
IDEX Token - https://auroradao.com
KuCoin Shares https://kcs.kucoin.com
Kyber Network https://kyber.network/about/knc
Loom https://loomx.io
Loopring https://loopring.org
Maker https://makerdao.com/en
Mithril https://mith.io/en-US
Nexo https://nexo.io
OmiseGO https://omisego.co
Orbs https://www.orbs.com
Paxos Standard https://www.paxos.com/pax
Polymath https://polymath.network
Populous https://populous.world
Pundi X https://pundix.com
Augur  https://www.augur.net
Revain - https://revain.org
STASIS EURS https://eurs.stasis.net
Status https://status.im/snt-utility
Tether USD https://tether.to
TrueUSD https://www.trusttoken.com/trueusd
USD Coin https://www.coinbase.com/usdc
Walton https://www.waltonchain.org/en
Wax Token https://wax.io
Zilliqa https://zilliqa.com

Binance DEX Projects:

- Gifto https://gifto.io
- Ankr Network https://www.ankr.com
- Bitcoin BEP2 https://bit.ly/2ZbbAzE
- Crypterium https://crypterium.com/crpt-token
- Cashaaa https://www.cashaa.com/CAS-banking-the-crypto

6) WALLETS ARE NOT CREATED EQUAL

- Real-time transaction fee estimator
- Segwit support for Bitcoin
- SPV-enabled
- Censorship-resistant
- Non-custodial
- No address reuse
- Wallet import/export
- Open source, https:/github.com/horizontalsystems

Be Free. Be Unstoppable.

**Comment by Dianaaiym** [comment]
already added on markets
https://play.google.com/store/apps/details?id=io.horizontalsystems.bankwallet
https://apps.apple.com/us/app/unstoppable-bitcoin-wallet/id1447619907?ls=1
