### ISSUE TITLE
Adopt wallet interface to be compatible with multiple Private Keys

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#28]
The team working on EOS blockchain is ready to start integration into the wallet. 

At this point we encountered situation where app can potentially hold multiple secret keys. As a result following app sections needs to change to support this concept:

- welcome screen: no longer relevant. the current version assumes that user has only one combination of keys. As result the starting screen should be a coin manager screen. 
- coin manager screen: instead of the DONE button at the top-right add fixed full-width button fixated at the bottom (instead of tab bar). Change the title of the controller to "Add Coins" (@Dianaaiym )
- create new section "Private Keys" in Security section. That section will list all private keys held by the app.. For each key we need an option to Unlink, Backup and at the same time need to see which coins that key supports.

**Comment by horsys** [comment]
already implemented
