### ISSUE TITLE
Lock Screen: Display latest prices in fiat

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#29]
Think of ways to show latest coin quotes on the lock screen itself.

**Comment by TalgatNurdinov** [comment]
<img width="1206" alt="Screen Shot 2019-09-06 at 6 16 08 PM" src="https://user-images.githubusercontent.com/42367908/64427355-e7ab8d00-d0d2-11e9-8a20-00cf412dcc2c.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=1633%3A1

<img width="1161" alt="Screen Shot 2019-09-06 at 6 18 19 PM" src="https://user-images.githubusercontent.com/42367908/64427374-f09c5e80-d0d2-11e9-8957-1ca7b1072d34.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=1633%3A92

**Comment by esengulov** [comment]
closed by mistake

**Comment by esengulov** [comment]
> <img alt="Screen Shot 2019-09-06 at 6 16 08 PM" width="1206" src="https://user-images.githubusercontent.com/42367908/64427355-e7ab8d00-d0d2-11e9-8a20-00cf412dcc2c.png">

While this looks good it will force all users to require one extra click on app open before the user can transition to the wallet. Doesn't feel right :)
