### ISSUE TITLE
Design Welcome Screens for the App

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#34]
Upon integration of the EOS wallet the current welcome screen to the wallet will be no longer relevant as the structure of the app will change after the integration.

We need 4 welcome screens to explain the user how to use the wallet:

1 - message: one wallet for all blockchains
2 - message: full control in user's hands
3 - message: easy backup/restore 
4 - message: the wallet has been created for the user.

**Comment by TalgatNurdinov** [comment]
<img width="1542" alt="Screen Shot 2019-07-02 at 5 17 00 PM" src="https://user-images.githubusercontent.com/42367908/60508784-3c0a4900-9ced-11e9-8d37-1abadd51c743.png">

**Comment by esengulov** [comment]
@TalgatNurdinov can you also provide an option with just one welcome screen, that will display the same graphic as on the site's header

**Comment by TalgatNurdinov** [comment]
https://zpl.io/bAWW3Lp
