### ISSUE TITLE
Coin Manager rework

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#35]
redesign coin manager to be more like on Exodus, check it out. Here is what we need:

- on/off switcher on the right, instead of +/- buttons
- move the coin icons to the left of the screen, next to name
- ~~coins that have the active key connected to the coin should have the key icon next to the on/off switcher~~
- for blockchains based tokens i.e. ERC20 display the token type next to toke symbol. ex: MCO (ERC20)
- add search field/icon to the top of the page for quick find
- the list should consist of a single section, sorted in alphabetical order
- remove the sorting options from coin manager
- click on a coin without a key should open bottom controller as shown below:
-- title: Add Key
-- text: You need to have a cryptographic key before you can add [coin_symbol] coin. 
-- button1: Create New
-- button2: I already have

**Comment by TalgatNurdinov** [comment]
https://zpl.io/2GyRo9E
https://zpl.io/ankZedx
https://zpl.io/2ZDvXj4
