### ISSUE TITLE
Sorting on Balance Tab

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#36]
Sorting logic:

- default sorting should always be "by value", for coins that have balance.
- coins that have balance but no rate should appear after the coin with balance and rates
- finally should be coins that have 0 balance, sorted by market cap(if rates available)
-  the sorting icon should appear after the user adds 5 coins. 
- sort by options
-- 24h volume
-- name
-- portfolio value
-- market cap
-- 24h change

**Comment by TalgatNurdinov** [comment]
done
