### ISSUE TITLE
Show Key / Backup steps for Keys

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#37]
In the coming update we are adding an option (in addition to backup) to view the Private Key for the user. The "SHOW" element should use same controllers as there Backup.

Backups Steps: 
Intro >> PIN >> Key >> Confirmation

Show steps:
PIN >> Key

**Comment by TalgatNurdinov** [comment]
https://zpl.io/a89BE3Q - android
https://zpl.io/a7dLGDq - ios
