### ISSUE TITLE
UI Improvements for Balance Tab

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#41]
- iOS ticket: https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/1130
- Android ticket: https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1393

- [x] When no coins selected the "Add Coins" button should appear at the center of the screen.

- [x] Syncing Indicator on Balance Tab needs to standout. At the moment it's only visible on expanded coin cell. I propose we make it visible even if the cell is closed. It can potentially make the current rate non-visible which is not an issue...

![IMG_3481](https://user-images.githubusercontent.com/8611762/65758018-1816a200-e13a-11e9-9ed7-7a2db8c20325.jpg)
![IMG_3482](https://user-images.githubusercontent.com/8611762/65758020-1816a200-e13a-11e9-9624-e21970168a26.jpg)

- [x] I think the current look of the graph buttons that appear on the coin cells doesn't look nice.

![IMG_3486](https://user-images.githubusercontent.com/8611762/65758796-7e4ff480-e13b-11e9-8dee-74030c0f88c7.PNG)

- [x] Would be nice to have only sorting button and try to get rid of the graph on/off. Maybe merge them into a single menu?

**Comment by TalgatNurdinov** [comment]
https://zpl.io/VOAxgrl
