### ISSUE TITLE
Error Screen: No OS PIN state

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#44]
In case when user removes the OS pin the app will show an error screen. This screen should display text and preferably some image above the text. No action buttons.

Text:

- android: This app requires that phone has the passcode (screen lock) enabled. You may enable it in Android settings.
- iOS: This app requires that phone has the passcode (screen lock) enabled. You may enable it in iOS settings.

**current state:**

![C521335D-99C0-4995-A664-F3110B54A438](https://user-images.githubusercontent.com/8611762/61706858-fcbe9d80-ad6a-11e9-91db-bf517a644540.jpg)
![photo_2019-07-23_16-53-32](https://user-images.githubusercontent.com/8611762/61706859-fd573400-ad6a-11e9-8b3a-e700abfd2d4d.jpg)

**Comment by TalgatNurdinov** [comment]
<img width="774" alt="Screen Shot 2019-07-24 at 4 53 28 PM" src="https://user-images.githubusercontent.com/42367908/61927743-ba2dd880-af97-11e9-9357-8cd583404c2f.png">

**Comment by TalgatNurdinov** [comment]
<img width="774" alt="Screen Shot 2019-07-26 at 3 00 21 PM" src="https://user-images.githubusercontent.com/42367908/61940163-a9408f80-afb6-11e9-9341-e23e2c08756e.png">

IOS
https://zpl.io/b6g46Aq
https://zpl.io/ag6QX1Z

ANDROID
https://zpl.io/VQQvp3R
https://zpl.io/bLWdg3Y
