### ISSUE TITLE
Settings >> Report A Problem

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#46]
This page should show simple show text version of the email (hsdao@protonmail.ch) where users may send issues/bugs with the wallet.

I think it should be last item on Settings page.

here are respective tickets on wallet repos:

- https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1137
- https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/871

**Comment by TalgatNurdinov** [comment]
<img width="365" alt="Screen Shot 2019-08-15 at 3 03 03 PM" src="https://user-images.githubusercontent.com/42367908/63085237-de654f80-bf6e-11e9-9c17-0182672be7f7.png">
<img width="380" alt="Screen Shot 2019-08-15 at 3 10 05 PM" src="https://user-images.githubusercontent.com/42367908/63085253-e32a0380-bf6e-11e9-9817-c58e34596892.png">

https://zpl.io/Vx6Kj9x
