### ISSUE TITLE
Send controller: Minor Design Changes

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#49]
- [x] provide a way to show full recipient address, both on send and send confirmation controller 
- [ ] address case for the title when the coin name is long i.e. Basic Attention Token. In case of languages where the 'Send' word is long the title may just fit to display the Send text.

**Comment by TalgatNurdinov** [comment]
- [ ] Send: Resizable Input form
- [ ] Confirm: New Amount cell component (will be used tx info controller)
- [ ] Confirm: Updated addresses copyist (Full / 2 lines / Shorted)
* Ignore new style of buttons

<img width="1270" alt="Screen Shot 2019-09-05 at 2 49 15 PM" src="https://user-images.githubusercontent.com/42367908/64326750-59f57200-cfec-11e9-9eae-afcdc51042b2.png">
<img width="859" alt="Screen Shot 2019-09-05 at 2 50 09 PM" src="https://user-images.githubusercontent.com/42367908/64326840-7a253100-cfec-11e9-8699-f2fad5dee8fe.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=222%3A436
