### ISSUE TITLE
UI Improvements for Chart View

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#52]
Chart View:

- [x] make graph line slightly bolder
- [x] make the font for % price change a bit thicker
- [x] the word 'price' in title should be in different font to make it standout from name (ex: Crypto.com Chain Price). The word price should have a different look to stand out from name
- [x] try to add somewhere below the graph the data source (source: CryptoCompare.com)
- [x] @ealymbaev suggested displaying the values below the graph (mkt cap, high, low) as a vertical list below the graph. I like that as well. Let's try that.
- [x] add 'in Circulation' and 'Trading Volume' entires, in addition to  (mkt cap, high, low)
- [x] make the selected state for period (1D, 7D, 1M etc) standout more (see below)
![IMG_3383](https://user-images.githubusercontent.com/8611762/64514399-5b84aa00-d30c-11e9-9770-c4405dd24ed0.jpg)

- [x] add a horizontal line to the top of the bottom controller as an indicator/hint that the controller is swipe-able :
-- receive
-- graph view
-- etc

![IMG_3382](https://user-images.githubusercontent.com/8611762/64506977-3e93ab00-d2fb-11e9-91df-058c40d7f3d3.jpg)

**Comment by TalgatNurdinov** [comment]
`make the font for % price change a bit thicker`
- For symbol should be used same font

`the word 'price' in title should be in different font to make it standout from name (ex: Crypto.com Chain Price). The word price should have a different look to stand out from name`
`add a horizontal line to the top of the bottom controller as an indicator/hint that the controller is swipe-able :`
- Bottom sheets headers was redesigned already

`@ealymbaev suggested displaying the values below the graph (mkt cap, high, low) as a vertical list below the graph. I like that as well. Let's try that.`
- We have less vertical space for bottom sheets (look at android)

`make the selected state for period (1D, 7D, 1M etc) standout more (see below)`
- on periods i use existing components, we can use the buttons that were before

**Comment by esengulov** [comment]
@TalgatNurdinov points below are still relevant 

Chart View:

- [ ] make the font for % price change a bit thicker. it's hard too read
- [ ] try adding 'set alert' button to graph view
- [ ] the word 'price' in title should standout from name (ex: Crypto.com Chain Price). 
- [ ] try to add somewhere the data source (source: CryptoCompare.com)
- [ ] @ealymbaev suggested displaying the values below the graph (mkt cap, high, low) as a vertical list below the graph.
- [ ] add 'in Circulation' and 'Trading Volume' entires, in addition to  (mkt cap, high, low)
- [ ] make the selected state for period (1D, 7D, 1M etc) standout more (see below)
- [ ] add a horizontal line to the top of the bottom controller as an indicator/hint that the controller is swipe-able : receive / graph view etc

**Comment by TalgatNurdinov** [comment]
<img width="407" alt="Screen Shot 2019-09-23 at 5 31 05 PM" src="https://user-images.githubusercontent.com/42367908/65424655-de8a2200-de2d-11e9-8871-6f51b22211ec.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3239%3A4061

**Comment by esengulov** [comment]
> <img alt="Screen Shot 2019-09-23 at 5 31 05 PM" width="407" src="https://user-images.githubusercontent.com/42367908/65424655-de8a2200-de2d-11e9-8871-6f51b22211ec.png">
> 
> https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3239%3A4061

@TalgatNurdinov looks good, but we need more changes. We need to add one more entry ()

- [ ] second Volume entry should be "in Circulation". 
- [ ] I think that some entries should span full row so that it can have longer texts texts as below. I propose to show High / Low on one row and the other 4 entries as single line

-- High: $10,300  ||  Low: $9,000  
-- Market Cap: $178.8 Billion
-- Trading Volume (24 hours): $2.32 Billion
-- Bitcoin in Circulation: 17.3 million BTC
-- Bitcoin in Total: 21 million BTC
-- source: @CryptoCompare.com

**Comment by TalgatNurdinov** [comment]
Android 
<img width="356" alt="Screen Shot 2019-10-07 at 2 55 03 PM" src="https://user-images.githubusercontent.com/42367908/66298091-d98b9f00-e912-11e9-9cd0-c08b69d2d42b.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3502%3A11535

iOS
<img width="366" alt="Screen Shot 2019-10-07 at 2 58 18 PM" src="https://user-images.githubusercontent.com/42367908/66298126-ea3c1500-e912-11e9-9b7a-e68dbf301f2e.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3495%3A216
