### ISSUE TITLE
Provide Final Layout Link for Notifications Manager screen

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#54]
- [x] Change cells to double line height, by displaying coin symbol below the title
- [x] need an option somewhere to deactivate all existing notifications.
- [x] figure out a better way to differentiate between active and inactive notifications
- [ ] add Figma link to iOS issue: https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/1141
- [ ] add Figma link to Android issue: https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1403

**Comment by TalgatNurdinov** [comment]
<img width="381" alt="Screen Shot 2019-09-23 at 6 21 59 PM" src="https://user-images.githubusercontent.com/42367908/65425115-0d54c800-de2f-11e9-9ebd-f750ec4bc2df.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3139%3A1664

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3139%3A1664

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=2975%3A68
