### ISSUE TITLE
Finalize HoprizontalSystems.io website look

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#60]

**Comment by TalgatNurdinov** [comment]
Information structure of hs website is ready.

Problems:
- No clarity structure, hard to understanding design.

Goals:
- Make design easy to understanding what we do and who we are
- Better segmentation of users
- Increase Subscribers with eBook guides
- Increase stars on Github
- Increse Installs

- Home page:  We encourage you to connect to the new network as a join to community. On the main page in two places we urge to sign, the button on the top and closer to the end the filling form.
- The next part is for segmentation of visitors and better conversion. 
Pages open for these individuals. The usual user enters the Application (installs), the advanced one enters the Guides (subscribes), and the developer considers the codes (put a star)
- After then grouped link for Contact / Follow / Donate


Please check the site and give feedback.
@kansalt You need to prepare a completed design for implementation by developers.
When finished let me know

**Comment by TalgatNurdinov** [comment]
Team section need more information for reliability
Think about it!

**Comment by TalgatNurdinov** [comment]
https://github.com/horizontalsystems/horizontalsystems.github.io/issues/36#issue-539529599
