### ISSUE TITLE
Balance Tab : minor design improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#64]
As the number of tokens supported by the app is growing we need to be able to differentiate between the same token on multiple blockchains i.e. Binance Token on Binance DEX from The Binance Token on Ethereum.

I propose following:

- [ ] both in collapsed/expanded coin cell append coin type next to coin symbol
-- if token is on Ethereum  >> [coin symbol](ERC20)
-- if token is on EOS >> [coin symbol](EOSIO)
-- if token is on Binance DEX >> [coin symbol](BEP2)

**Comment by TalgatNurdinov** [comment]
<img width="374" alt="Screen Shot 2019-11-15 at 12 06 50 PM" src="https://user-images.githubusercontent.com/42367908/68920754-735f2b00-07a0-11ea-8390-42209b41e33b.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3553%3A70
