### ISSUE TITLE
Chart View improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#65]
- [ ] rename the Volume entry to Volume(24h)
- [ ] remove the horizontal bar values and expand the chart to cover entire controller width
- [ ] the high/low amounts should appear on the graph itself

**Comment by TalgatNurdinov** [comment]
on pressed state high/low amounts should be disabled
<img width="380" alt="Screen Shot 2019-11-05 at 2 30 58 PM" src="https://user-images.githubusercontent.com/42367908/68191091-e9ada180-ffd8-11e9-8b09-1ab79ac109d6.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3495%3A217
