### ISSUE TITLE
Welcome Screen Graphic

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#66]
the Unstoppable lady graphic appears too large (giving an impression of being zoomed) on large resolution devices (iPhone Pro Max, Xiaomi Mi Max)

**Comment by TalgatNurdinov** [comment]
<iframe style="border: none;" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2Fp8oB6wTgeqJihiN2l87A3n%2FUnstoppable-Design-System%3Fnode-id%3D5589%253A45%26viewport%3D264%252C1447%252C0.5%26scaling%3Dscale-down" allowfullscreen></iframe>
