### ISSUE TITLE
Redesign the layout on wallet Create/Restore to enable creation restore of BIP44/BIP49/BIP84 wallet types

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#68]

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=4102%3A357

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=4102%3A357
