### ISSUE TITLE
Chart View Improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#70]
- [x] extend the chart area to cover the whole width of the scree
- [x] remove the numbers on the vertical axis
- [x] display the max/low values on the graph itself

**Comment by TalgatNurdinov** [comment]
<img width="380" alt="Screen Shot 2019-11-05 at 2 30 58 PM" src="https://user-images.githubusercontent.com/42367908/69527096-c6519300-0f95-11ea-8b81-47b536014a48.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3495%3A217
