### ISSUE TITLE
 Illustration / Graphics for Libra EBook

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/HS-Design#75]
Design visual language style for ebooks, i'm thought it should be like newsletter magazine.
with bright and fun colors / humorists pictures, used easy to understand analogies for pictures

- [ ] Need Cover illustration for guides 
      - Libra in Simle Terms  
        (Bitcoin Explained in Simple Terms should be same style)

- [ ]  Illustration and graphs for Libra in ST ebook

graphics example
![rising](https://user-images.githubusercontent.com/42367908/70879987-a9870900-1ff1-11ea-9525-eb419debbc71.jpg)
![reseller](https://user-images.githubusercontent.com/42367908/70879989-aa1f9f80-1ff1-11ea-85f6-6b1018cef8a3.png)
![one-against-all](https://user-images.githubusercontent.com/42367908/70879991-aa1f9f80-1ff1-11ea-86c7-9049d394d768.jpg)
![fb-reach](https://user-images.githubusercontent.com/42367908/70879992-aab83600-1ff1-11ea-95c4-8aa8dbd0b142.png)
![libra-structure](https://user-images.githubusercontent.com/42367908/70879993-aab83600-1ff1-11ea-931e-8d8299a5a4da.jpg)
![capital-inflow-bitcoin](https://user-images.githubusercontent.com/42367908/70879994-aab83600-1ff1-11ea-804b-8b1f5e564cdf.jpg)
![people-effect](https://user-images.githubusercontent.com/42367908/70879995-ab50cc80-1ff1-11ea-86ed-216b73fc5b31.jpg)

**Comment by kansalt** [comment]
https://www.figma.com/file/zkbIpUQh3TVs7yQJpPgbcv/Unstoppable-Books-Template?node-id=65%3A85
