### ISSUE TITLE
Chart view Improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#80]
Consider following modifications:

- [ ] remove 'price' from title
- [ ] add volume charts
- [ ] consider placing timestamp on the same line where price is shown, instead of displaying it under title. Showing it next to price would hint user that the price was taken on that timestamp.

**Comment by TalgatNurdinov** [comment]
<img width="393" alt="Screen Shot 2020-01-22 at 6 24 10 AM" src="https://user-images.githubusercontent.com/42367908/72854845-db217d00-3cdf-11ea-8b48-2aac95d00ece.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=1406%3A237

**Comment by TalgatNurdinov** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/1518#issuecomment-576951152
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1820#issuecomment-576951800
