### ISSUE TITLE
 coin charts: display latest coin news

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#84]
remove not-ready label from issues below when ready

- [x] https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/1588
- [x] https://github.com/horizontalsystems/unstoppable-wallet-android/issues/1923

@TalgatNurdinov also keep coin mind that soon we will need to link coin reports/guides from somewhere in the wallet. I think charts controller is a good candidate for that.

**Comment by TalgatNurdinov** [comment]
<img width="842" alt="Screen Shot 2020-02-26 at 10 07 52 AM" src="https://user-images.githubusercontent.com/42367908/75311073-df612d00-587f-11ea-8b3b-c5b65880dd18.png">
<img width="799" alt="Screen Shot 2020-02-26 at 10 07 43 AM" src="https://user-images.githubusercontent.com/42367908/75311077-e38d4a80-587f-11ea-9eed-2d0b88922d42.png">
