### ISSUE TITLE
Redesign alert for create eos

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/HS-Design#87]
![2020-05-06 11 47 54](https://user-images.githubusercontent.com/22589457/81141817-8f919700-8f8f-11ea-9ef0-812294eac028.jpg)

**Comment by TalgatNurdinov** [comment]
IOS - https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=9748%3A930

Android - https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=9748%3A1207

<img width="381" alt="Screen Shot 2020-05-06 at 3 04 05 PM" src="https://user-images.githubusercontent.com/42367908/81159511-d93bab00-8faa-11ea-9ae0-fceb377760ac.png">
