### ISSUE TITLE
Bankwallet.app >> Unstoppable.money

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/HS-Design#9]
Let's try to rebrand the wallet from BankWallet.app to Unstoppable.money.

Please design the new layout for the website as per our discussions. The keyword "Unstoppable" is the KEY element in the design and subsequently the branding of the wallet.

**Comment by TalgatNurdinov** [comment]
<img width="620" alt="Screen Shot 2019-05-03 at 11 12 04 AM" src="https://user-images.githubusercontent.com/42367908/57120815-a2c6c100-6d95-11e9-9c04-70a631c5b8a3.png">
https://zpl.io/aRx8ZPz
