### ISSUE TITLE
FAQ design

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/HS-Design#91]
FAQ layouts for Wallet app and wallet site

**Comment by kansalt** [comment]
IOS and Android versions https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=23457%3A0

Web version https://www.figma.com/file/bxLCVEqTGuS9sBsNfUjMkl/new-Unstoppable-Wallet?node-id=7992%3A41
