### ISSUE TITLE
Swap: entering amount in base currency

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/HS-Design#94]
- Prepare opportunity for entering amount in base currency.
- Implement last version of displaying data from uniswap
- Swap components

**Comment by TalgatNurdinov** [comment]
**Android layouts**
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=22077%3A10557

**Comment by kansalt** [comment]
IOS Layouts
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=22050%3A2377
