### ISSUE TITLE
Join Community Page Design

### ISSUE THREAD

**Issue by Dadybayo** [horizontalsystems/HS-Design#95]
Like Solana Page

**Comment by Dadybayo** [comment]
Join the Unstoppable Wallet Community

**Comment by kansalt** [comment]
https://www.figma.com/proto/bxLCVEqTGuS9sBsNfUjMkl/new-Unstoppable-Wallet?node-id=9970%3A2586&viewport=1047%2C503%2C0.06863463670015335&scaling=min-zoom
