### ISSUE TITLE
FAQ localization

### ISSUE THREAD

**Issue by Dadybayo** [horizontalsystems/HS-Design#96]
Translate FAQ to other languages that support Unstoppable Wallet

**Comment by TalgatNurdinov** [comment]
@Dianaaiym 
[FAQ - images Android.zip](https://github.com/horizontalsystems/HS-Design/files/5595815/FAQ.-.images.Android.zip)

**Comment by kansalt** [comment]
@Dianaaiym 
[FAQ - images IOS.zip](https://github.com/horizontalsystems/HS-Design/files/5596278/FAQ.-.images.IOS.zip)
