### ISSUE TITLE
Sending to domain address

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/HS-Design#98]
- Address input should be editable for entering fio (unstoppable.crypto).
- Also need the spinner for validating after entering name.
- Error should be shown same as like invalid address

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=23755%3A76107

**Comment by kansalt** [comment]
IOS layouts
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=9319%3A178
